### ISSUE TITLE
Support expo-constants in Metro web

### ISSUE THREAD

**Issue by cseelus** [expo/router#137]
### Summary

{Constants.manifest} is `{}` on web platform, so there is for example no way to get the current version number via `{Constants.manifest.version}`

### Minimal reproducible example

`npx create-react-native-app -t with-router`

Input `expoconstants` when asked for the app name.

`cd expoconstants `

`yarn expo install expo-constants`

`yarn web`

`touch app/index.js`

Then in `App.js` add 

```javascript 
import { Text } from 'react-native'
import Constants from 'expo-constants'

export default function Home() {
  return (
    <Text>{JSON.stringify(Constants.manifest)}</Text>
  )
}
```

**Comment by bombillazo** [comment]
If you're using Next.js,  need to import the app-config manually when running webpack.

**Comment by EvanBacon** [comment]
Ya we don't currently support this feature in Metro web, I'm not sure if it really makes sense to add the feature since the app.json is pretty large and web bundles should be as small as possible. You could use something like [react-native-dotenv](https://github.com/goatandsheep/react-native-dotenv) (which we really should just add to Expo CLI by default).

**Comment by erisvaldojunior** [comment]
+1 on this. Guess not supporting it make things a bit weird since changing from webpack to metro web breaks all constant.manifest references in the code.

**Comment by EvanBacon** [comment]
Fixed in https://github.com/expo/router/pull/189
