### ISSUE TITLE
RootContainer onStateChange causes re-render loop

### ISSUE THREAD

**Issue by tyrauber** [expo/router#170]
### Summary

While attempting to integrate [react-naviation screen analytics](https://reactnavigation.org/docs/screen-tracking/) using `onReady` and `onStateChange` on `RootContainer`, I hit the following error:

> Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.

After some investigation, it seems calling `RootContainer.useRef()` in the parent component and adding any `onStateChange` method to `<RootContainer/>` causes the parent component to re-render endlessly.

I also noticed the `onReady` handler is not firing. The [only contextProps here](https://github.com/expo/router/blob/main/packages/expo-router/src/ContextNavigationContainer.tsx#L83) are `children`, even if an `onReady` prop is set on `RootContainer`. It seems like the component renders once prior to `setProps` on the `useNavigationContainerContext` context being called, and doesn't update once the context changes.

Any suggestions on how to use the ref from RootContainer within the `onReady` and `onStateChange` handlers?  Would love to integrate screen tracking with expo-router.

Thanks a bunch!

### Minimal reproducible example

```
function RootLayout() {
  const navigationRef = RootContainer.useRef()
  const routeRef = React.useRef()
  console.log('render')
  return (
    <>
    <RootContainer 
      onReady={() => {
        console.log('onReady')    
        routeRef.current = navigationRef?.current?.getCurrentRoute()
      }}
      onStateChange={async () => {
         const previousRoute = routeRef.current
         const currentRoute = navigationRef?.current?.getCurrentRoute()
         if (currentRoute?.name as boolean && previousRoute?.name !== currentRoute?.name) {
           console.log('onStateChange', currentRoute)

         }
        routeRef.current = currentRoute
      }}
    />
      <Layout/>
    </>
  );
}
```

**Comment by EvanBacon** [comment]
Taking a step back, screen tracking should be done using the URL or state directly. This is unique to `expo-router` because we can ensure a URL will always exist.

```js
function Layout() {
  const { href } = useHref();

  useEffect(() => {
    // track `href`
  }, [href]);

  return <Children />
}
```

Seems like we should drop support for `onReady` in favor of `useEffect(() => { rootState }, [rootState])` because the order of `onReady` could cause some issues with multiple `<RootContainer />` elements.

If you don't invoke `onReady` in time then you miss it, if you invoke `onReady` every time the method changes, then you may end up with an issue where the best-effort initial state could change unexpectedly. We could expose a mock `onReady` which is tracked and only ever invoked once, but this would only exist for migration which isn't great given users may need to reconsider why they're using certain React Navigation functions to begin with.

I'd prefer we just replace:

- `onReady` -> `useRootNavigation`
- `onStateChange` -> `useRootNavigationState`

and the screen tracking guide should be reimplemented to follow the above recommendation. 

The developer should mostly only ever be concerned with the current URL, the URL with conventions in-tact (`/(app)/index`), and the query parameters. This comes with the exception of drawers which could be open/closed or tabs which could be selected without resetting a deeply nested stack, in both cases local navigation state is required.

I'll open some PRs to document the preferred systems, warn users about docs, and prevent recursive loops from the uninformed API choices I originally put in place.

**Comment by tyrauber** [comment]
This is super helpful, @EvanBacon, thank you! 

I appreciate the explanation of why it was happening, but also the proposed alternative. Using the `useHref` hook is obvious in hindsight. Not sure how I missed that.

This approach is really nice. 

```
function Layout() {
  const url = useRef();
  const referrer = useRef();
  const { href } = useHref();

  useEffect(() => {
    if(href !== url){
      referrer.current = url.current
      url.current = href
    }
  }, [href]);

  return <Children />
}

```

It's cleaner than using the navigator's `onReady` and `onStateChange` handler, and the screen tracking logic can be set anywhere within the app.  

Can you expand up on this though?

> The developer should mostly only ever be concerned with the current URL the URL with conventions in-tact (/(app)/index), and the query parameters. This comes with the exception of drawers which could be open/closed or tabs which could be selected without resetting a deeply nested stack, in both cases local navigation state is required.
