### ISSUE TITLE
SplashScreen + custom font raises 'font not loaded …' error

### ISSUE THREAD

**Issue by cseelus** [expo/router#276]
### Summary

Using `SplashScreen` [as recommended in the docs](https://expo.github.io/router/docs/features/splash), together with a custom font (https://github.com/expo/google-fonts), raises an error `XY is not a system font and has not been loaded through …`.

Expected result:

![IMG_8398](https://user-images.githubusercontent.com/3188392/218220541-c556ea31-1fe6-4709-8346-41f24fb717d1.jpeg)

Actual result:

https://user-images.githubusercontent.com/3188392/218219895-893d4a9f-d31e-4691-b584-7269b34ee071.mov

### Minimal reproducible example

https://github.com/cseelus/explo-splashscreen-fonts

Edit: Using `<Splashscreen />` in different ways like `if(!fontsLoaded) return <SplashScreen />` will lead to it being hidden too early/flickering.

**Comment by EvanBacon** [comment]
Thanks for the detailed report.

This is indeed an error, I think it should be fixed in React Native and Expo upstream. Using any unloaded font shouldn't throw an error, we've landed [a fix in React Native](https://twitter.com/motiz88/status/1623788453673435142?s=20&t=WoPxdXfXH8IsMvBobzAVIQ).

Possibly need to do the same for [usage in the Expo Go app](https://github.com/expo/expo/blob/b52e368f2ee0b8cd89be806fe26cafd29747d883/packages/expo-font/src/Font.ts#L31-L43).

**Comment by erasmuswill** [comment]
Custom fonts are currently working in development builds. The only difference I'm seeing is that I am returning only <SplashScreen/>, and not returning it as part of the component containing the fonts I want to render.

**Comment by EvanBacon** [comment]
This is fixed in dev clients and production builds in Expo SDK 49. The console.error is still shown in Expo Go though, but it's benign.

**Comment by EvanBacon** [comment]
Fully resolved in SDK 50
