### ISSUE TITLE
Function goes into loop when adding router as a dependency

### ISSUE THREAD

**Issue by ak151997galaxy** [expo/router#288]
### Summary

hello!
In our app, we created a custom hook and returned a function. 
When we add a router to the dependency array, function goes into a loop and after removing the router from the dependency array it works fine.

### Minimal reproducible example

This will help in understanding the problem.
![Screenshot from 2023-02-15 18-46-52](https://user-images.githubusercontent.com/104891451/219103371-476c74e3-56a9-4a5c-95d9-e3e4d585b48a.png)

**Comment by EvanBacon** [comment]
screenshots of code are not accepted as reproducible examples. Please provide code that can be downloaded and ran.

**Comment by javascripter** [comment]
I think it's caused by this line of code where the router object is not memorized.
If the router object is not memoized, any re-render will cause all effects with router dependencies to be re-run, creating an unintended infinite loop easily.

https://github.com/expo/router/blob/f044f8926c966de746da82127e9cd09e4d1268a9/packages/expo-router/src/hooks.ts#LL35C1-L35C7
