### ISSUE TITLE
'?' character truncates params passed via router.push

### ISSUE THREAD

**Issue by RohovDmytro** [expo/router#345]
### Summary

Consider this code:
````
router.push({
  pathname: 'auth',
  params: {
    autoAuthProvider: 'anonymous',
    title: i18n.t('questionAuthToBackup'),
    mode: 'account-creation',
    providers: ['google', 'apple', 'anonymous'],
  },
})
````

### Minimal reproducible example

If the `title` contains the question mark, the `useSearchParams` hook does not return `mode` and `providers` and the question mark character gets truncated from `title`.

**Comment by likeSo** [comment]
I got the same question (maybe?).
Once I pass a URL to the `params`, such as:
`http://localhost:19000/product/detail/2058?id=2058&imageUri=https://xxx.xxxxx.com/01/20220424/1524515934590/origin.png`

The whole website refreshes every time the route changes. After i remove the  `imageUri` parameter, It works very well

I am not a web developer, maybe it is because of hash or something?

**Comment by RohovDmytro** [comment]
Try encoding `imageUri` prop into the string (encodeURIComponent) and then decoding it wherever you read the value.
