### ISSUE TITLE
Bug handling deep links

### ISSUE THREAD

**Issue by RohovDmytro** [expo/router#362]
### Summary

`expo-router` does not properly handle deep linking.

### Minimal reproducible example

````javascript
import { useEffect, useState } from 'react';
import URL from 'url-parse';

import { State } from './fork/getPathFromState';
import { useLinkingContext } from './link/useLinkingContext';

function useResolvedPromise<T>(promise: Promise<T> | undefined) {
  const [resolved, setResolved] = useState<T | undefined>();

  useEffect(() => {
    if (promise) {
      promise.then(setResolved);
    }
  }, [promise]);

  return resolved;
}

export function useInitialRootState() {
  const linking = useLinkingContext();
  const url = useResolvedPromise(linking.getInitialURL() as Promise<string>);
  const [state, setState] = useState<State | null>(null);

  useEffect(() => {
    if (url) {
      const parsed = URL(url);
      // TODO: Add hashes to the path
      const urlWithoutOrigin = parsed.pathname + parsed.query;
      console.log(parsed);
      console.log(urlWithoutOrigin);
      setState(linking.getStateFromPath(urlWithoutOrigin, linking.config)!);
    }
  }, [url, linking]);

  return state;
}
````

Let's say the proper `url` that the app was launched from is derived from this call:

````
 npx uri-scheme open "com.houserion.debug://invitation?code=123" --android
````

In this case `urlWithoutOrigin` will be quite messed up. Here are the logs printed to the terminal:

````json
{"auth": "", "hash": "", "host": "invitation", "hostname": "invitation", "href": "com.houserion.debug://invitation?code=123", "origin": "null", "password": "", "pathname": "", "port": "", "protocol": "com.houserion.debug:", "query": "?code=123", "slashes": true, "username": ""}

````

````
?code=123
````

**Comment by RohovDmytro** [comment]
P.S. Also, if I will mess up with the source code and hardcode `urlWithoutOrigin` to be 'invitation' (or `/invitation`) I still cannot open the app with a proper screen via deep link.

**Comment by mauricedoepke** [comment]
I encountered the same problem and I think I tracked it down to the function: `extractExpoPathFromURL`

The problems there seems to be that app urls and web urls are parsed in the same way to extract the parse.
It drops the hostname part for all urls which is right for web urls but not for app urls. This leads to:
```
https://mydomain/some/path -> some/path ✅
myapp://some/path -> path ❌
```

This was probably not found before, because there is a special case implemented for the expo go client, which works.

I guess one has to implement a distinction between those two types of urls depending on the protocol.

**Comment by mauricedoepke** [comment]
I encountered the same problem.

The issue there seems to be that app urls and web urls are parsed in the same way to extract the parse.
It drops the hostname part for all urls which is right for web urls but not for app urls. This leads to:
```
https://mydomain/some/path -> some/path ✅
myapp://some/path -> path ❌
```
I guess one has to implement a distinction between those two types of urls depending on the uri scheme.

When tracking this down deeper I also found the function: `extractExpoPathFromURL` which has a similar issue.
While locally trying to fix this it seems, that a fix in `useInitialRootState ` does not seem to have any impact on the behaviour of the app. Fixing it in `extractExpoPathFromURL` however has.

This was probably not found before, because there is a special case implemented in `extractExpoPathFromURL` for the expo go client, which works and was probabbly used for developing so far.

I think it might make sense to implement another special case in 'extractExpoPathFromURL' that compares the url protocol with the scheme in `Constants.expoConfig?.scheme` and keeps the "hostname" as path part if they match.

Maybe one could then reuse the `extractExpoPathFromURL` function inside `useInitialRootState` to have one unified url handling everywhere.

**Comment by RohovDmytro** [comment]
I've used your code to create a temporary patch to test things out via `patch-package`:

````
diff --git a/node_modules/expo-router/src/fork/extractPathFromURL.ts b/node_modules/expo-router/src/fork/extractPathFromURL.ts
index 000920b..6076724 100644
--- a/node_modules/expo-router/src/fork/extractPathFromURL.ts
+++ b/node_modules/expo-router/src/fork/extractPathFromURL.ts
@@ -13,10 +13,16 @@ export function extractExpoPathFromURL(url: string) {
   }
 
   const res = Linking.parse(url);
+  const isAppUrl = Constants.expoConfig?.scheme === res.scheme;
+
   const qs = !res.queryParams
     ? ""
     : Object.entries(res.queryParams)
         .map(([k, v]) => `${k}=${v}`)
         .join("&");
-  return (res.path || "") + (qs ? "?" + qs : "");
+  return (
+    (isAppUrl && res.hostname ? res.hostname + "/" : "") +
+    (res.path || "") +
+    (qs ? "?" + qs : "")
+  );
 }
\ No newline at end of file
diff --git a/node_modules/expo-router/src/useInitialRootState.native.tsx b/node_modules/expo-router/src/useInitialRootState.native.tsx
index e4b730a..325ff97 100644
--- a/node_modules/expo-router/src/useInitialRootState.native.tsx
+++ b/node_modules/expo-router/src/useInitialRootState.native.tsx
@@ -1,6 +1,6 @@
 import { useEffect, useState } from "react";
-import URL from "url-parse";
 
+import { extractExpoPathFromURL } from "./fork/extractPathFromURL";
 import { State } from "./fork/getPathFromState";
 import { useLinkingContext } from "./link/useLinkingContext";
 
@@ -23,10 +23,8 @@ export function useInitialRootState() {
 
   useEffect(() => {
     if (url) {
-      const parsed = URL(url);
       // TODO: Add hashes to the path
-      const urlWithoutOrigin = parsed.pathname + parsed.query;
-
+      const urlWithoutOrigin = extractExpoPathFromURL(url);
       setState(linking.getStateFromPath(urlWithoutOrigin, linking.config)!);
     }
   }, [url, linking]);

````

Seems working fine ATM. Will update if anything.

**Comment by RohovDmytro** [comment]
@EvanBacon , still does not work.

I've used later expo-router, 1.3.0, and opened a deep link with npx uri-scheme.

The `extractExpoPathFromURL` fail to parse link properly.

```
const res = Linking.parse(url);
````

=>

```
{"hostname": "invitation", "path": null, "queryParams": {"code": "***"}, "scheme": "com.houserion.debug"}
```

**Comment by RohovDmytro** [comment]
So
`com.houserion.debug://invitation/area?code=***`

=>

````
 LOG  {"hostname": "invitation", "path": "area", "queryParams": {"code": "***"}, "scheme": "com.houserion.debug"}
````
