### ISSUE TITLE
Expo router quick start error when running android on an emulator: expo-router/entry

### ISSUE THREAD

**Issue by coycoylaniba** [expo/router#427]
### Summary

While resolving module `expo-router/entry`, the Haste package `expo-router` was found. However the module `entry` could not be found within the package. Indeed, none of these files exist:

* `D:\programming\test\expo-router\entry(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)`
  * `D:\programming\test\expo-router\entry\index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)`

OS: Windows 11
Node: 18.14.2
Android Studio: 2022.1

### Minimal reproducible example

npx create-expo-app@latest --example with-router
yarn start
Press a │ open Android

**Comment by MarkKewley** [comment]
Also experiencing this issue, I even tried mimicking some of their demo's but kept encountering this issue.

OS: Mac M2 Ventura 13.2.1
Node: Tried both v16.18.1 and v18.15.0
iOS Simulator: iPhone 14 Pro Max

Same example as above

**Comment by marklawlor** [comment]
From your error message, it appears NodeJS is looking at `D:\programming\test\expo-router\entry` instead of inside your `node_modules`.

Make sure you don't have a folder called `expo-router` in the top level of your project. NodeJS's module resolution algorithm first checks the current working directory. So by creating a folder called `expo-router` you will override your `node_modules/expo-router`.
