### ISSUE TITLE
iOS Swipe Back After Reset

### ISSUE THREAD

**Issue by alkhatera** [expo/router#444]
### Summary

When using `router.reset(“/home”)` on iOS, the user can swipe back to return to previous route. 

Expected behavior:
User should be prevented from swiping back after using reset

### Minimal reproducible example

1. Use `router.reset(“/any_route”)`
2. Swipe back on iOS

**Comment by EvanBacon** [comment]
`router.reset` is not a function. `router.replace` will push a screen without appending to the history, this only works in cases where the screen can be replaced, e.g. if you "replace" from the twitter profile to a Tweet, there will always be a history since the Tweet screen has to have a back button. https://expo.github.io/router/docs/features/linking/#userouter
