### ISSUE TITLE
RequireContext "id" type not compatible with new webpack-env type

### ISSUE THREAD

**Issue by nkeil** [expo/router#633]
### Which package manager are you using? (Yarn is recommended)

Yarn v3

### Summary

I'm getting a type error when trying to pass in the result of `require.context` into the `context` prop of `ExpoRoot`. I think I've tracked this down to [this file](https://github.com/expo/router/blob/ce766c7c2bfc94a5351091cdb1dac65b970183ae/packages/expo-router/src/types.ts#L4), which doesn't align with the newest webpack-env type [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webpack-env/index.d.ts) (version 1.18.1).

I.e. the line `id: string;` should be changed to `id: string | number;`

### Minimal reproducible example

With a simple file like this (using @types/webpack-env version 1.18.1):
```tsx
import { registerRootComponent } from "expo";
import { ExpoRoot } from "expo-router";

export function App() {
  const ctx = require.context("./src/app");
  return <ExpoRoot context={ctx} />;
}

registerRootComponent(App);
```
I'm getting this error:
```
Type '__WebpackModuleApi.RequireContext' is not assignable to type 'import("expo-router/build/types").RequireContext'.
  Types of property 'id' are incompatible.
    Type 'ModuleId' is not assignable to type 'string'.
      Type 'number' is not assignable to type 'string'.ts(2322)
```

**Comment by marklawlor** [comment]
`require.context` is a non-standardised bundler specific function that both Metro and Webpack have implemented. Due to implementation differences, they have different types. As Expo Router only supports bundling with Metro, I'm assuming that you are using Webpack for a different application within the same repo? If so I would recommend using a mono-repo setup to separate the dependencies. Alternatively you can use `skipLibCheck: true` in your `tsconfig.json` ([which is recommended to enable](https://www.typescriptlang.org/tsconfig#skipLibCheck)) to skip type checking dependencies in your `node_modules`.
