### ISSUE TITLE
Bug: Cannot redirect/push to sibling route inside (group)/_layout

### ISSUE THREAD

**Issue by marklawlor** [expo/router#793]
### Which package manager are you using? (Yarn is recommended)

None

### Summary

Redirecting within a group's layout will cause errors.

```
    console.error
      The action 'REPLACE' with payload {"name":"should-work"} was not handled by any navigator.
      
      Do you have a screen named 'should-work'?
      
      If you're trying to navigate to a screen in a nested navigator, see https://reactnavigation.org/docs/nesting-navigators#navigating-to-a-screen-in-a-
nested-navigator.
      
      This is a development-only warning and won't be shown in production.
```

Most likely caused by `isMovingToSiblingRoute` incorrectly detecting the group of the last state

### Minimal reproducible example

```
it("can redirect within a group layout", () => {
  renderRouter({
    "(group)/_layout": function Component() {
      const pathname = usePathname();

      if (pathname === "/") {
        return <Redirect href="/should-work" />;
      }

      return <Stack />;
    },
    "(group)/index": () => <Text />,
    "(group)/should-work": () => <Text />,
  });

  expect(screen).toHavePathname("/should-work");
});
```

**Comment by haikov** [comment]
> Most likely caused by isMovingToSiblingRoute incorrectly detecting the group of the last state

I believe I'm facing the same issue with navigating to the nested stack without the group, having the following structure and trying to navigate from `index` to `/substack`

![CleanShot 2023-07-23 at 14 35 39](https://github.com/expo/router/assets/9068073/0d352d92-b757-4031-aae3-4d6bd6915dd8)

When debugging router code I've found that `isMovingToSiblingRoute` gets the wrong `targetRoute` here https://github.com/expo/router/blob/main/packages/expo-router/src/link/stateOperations.ts#L54 because `targetState.routes` is an array of 2 element where first one is `index` and second is the correct `substack` route. Hence it tries to navigate to `substack` inside the current stack, which is not there.

Reverting changes made in this PR fixes the mentioned issue https://github.com/expo/router/pull/532

**Comment by devoren** [comment]
Any updates? Do we need to revert the changes as @haikov said, or should we wait for a fix or v3?

**Comment by adesugbaa** [comment]
Wow. Been pulling out my hair cause notification will not open a tab unless the user has previously navigated to said tab route. Any fix?

**Comment by joaomantovani** [comment]
Facing the same issue

**Comment by MarcusOhman91** [comment]
Kind of major not being able to jump to a parent or sibling stack using `router.replace`, broke a lot of stuff in my app. Two months and not fixed in a stable version? Worrying :confused: 

I could make it work by using `router.push` instead on those occasions. Surprisingly this made no difference in behaviour. My reason to use `router.replace` in the first place was to prevent user from being able to go back. Now using `router.push` to jump to a parent or sibling stack it still does not work going back, is this expected?

**Comment by z1haze** [comment]
Same issue here, except it occurs also with `router.replace` and the `<Redirect/>` component when attempting to navigate to a child from from a parent layout

**Comment by Pcummings** [comment]
Seeling the same issue

**Comment by devoren** [comment]
It works fine! But in web when i use replace, i can go back. Is this a bug or behavior of expo routers?

**Comment by HerpGuy88** [comment]
Broken again in expo-router v3.

**Comment by pjmvp** [comment]
Indeed... First time using expo and expo-router, so I don't know if this is a re-ocurring issue, but I'm also experiencing problems with navigate() and replace().

e.g. For a structure like

- (app)
  - user
    -  [userId]
       - _layout.tsx
       - tab1.tsx
       - tab2.tsx
    - index.tsx

when in index.tsx (/user/) I'm unable to do router.navigate(`user/${userId}`) (or to use a <Redirect href={`user/${userId}`} /> which should achieve the same result). Nothing happens.

Shouldn't this be re-opened, or a new issue created?

**Comment by z1haze** [comment]
> Indeed... First time using expo and expo-router, so I don't know if this is a re-ocurring issue, but I'm also experiencing problems with navigate() and replace().
> 
> e.g. For a structure like
> 
> * (app)
>   
>   * user
>     
>     * [userId]
>       
>       * _layout.tsx
>       * tab1.tsx
>       * tab2.tsx
>     * index.tsx
> 
> when in index.tsx (/user/) I'm unable to do router.navigate(`user/${userId}`) (or to use a <Redirect href={`user/${userId}`} /> which should achieve the same result). Nothing happens.
> 
> Shouldn't this be re-opened, or a new issue created?

run away. run away as fast as you can. the expo-router is a cancer. use react-navigation instead, your mental health will thank you

**Comment by vonkanehoffen** [comment]
This is a problem I just had too, in `"expo-router": "~3.5.18",` 
Got round it via `router.navigate("/whatever")` in a `useEffect` hook, but `<Redirect href="/whatever" />` just took the user to a blank screen. The target never rendered.

So frustrating as I really like the `expo-router` API but it just seems to have so many bugs.

**Comment by upnorth** [comment]
Just managed to fix a related issue. Got some runcondition issues but it seemed to help to wrap the redirects (no return <Element>) in a useEffect that depended on all the conditional things. That way react seem to be able to run things in correct order. I just had a simple if-statement in the component before that.

Using expo-router ~3.5.23

**Comment by upnorth** [comment]
Just discovered that I had to do both redirect/replace as well as an empty render for the time it takes for the app to load the next page. Kind of annoying that the router doesn't abort renders until the routing process is finished, but it seems to be working at least.
