### ISSUE TITLE
expo-router does not play nice with jsc engine

### ISSUE THREAD

**Issue by RohovDmytro** [expo/router#795]
### Which package manager are you using? (Yarn is recommended)

npm

### Summary

Switch engine to `jsc` breaks things apart.

Screenshot:
![image](https://github.com/expo/router/assets/1548235/87906952-e4ec-40aa-b4e5-7e679d62a472)

### Minimal reproducible example

1. `npx create-expo-app@latest --template tabs@49 expo-router-issue-jsc`
2. Update app config to use to jsc
3. `npx expo start --android`
4. Observer error
5. Update `package.json` to use custom `app/index.js` file
6. Render simple component bypassing `expo-router`
```javascript
import { Text } from 'react-native';
import { registerRootComponent } from 'expo';

registerRootComponent(() => {
  return <Text>Wow</Text>
});
````

7. `npx expo start --android`
8. The app works as intended.

**Comment by EvanBacon** [comment]
Works on iOS, meaning something is probably wrong with the engine on Android. Can't be fixed in expo-router.

**Comment by israelidanny** [comment]
@EvanBacon I realize that the fix is probably not to be done right here, but it would still be very useful to know where to start going after the fix. Because this dependency and another one have me playing "catch-22" where one wants to force some features on me that `hermes` doesn't support yet, and this one makes it impossible to use `jsc`.

Any idea on where to start? My guess is that it either has issues with a nullish coalescing operator or optional chaining?
