### ISSUE TITLE
feat(docs): document how to setup traditional web modals

### ISSUE THREAD

**Issue by EvanBacon** [expo/router#83]
Modals like the ones found in the [Instagram website](https://www.instagram.com/p/CfZIX3oj6qN/) are pretty common on the web. We should document how to easily create this transparent floating effect for web-only cases:
<img width="1083" alt="Screen Shot 2022-10-14 at 2 41 10 PM" src="https://user-images.githubusercontent.com/9664363/195948267-683eb86e-96cf-498f-b5dd-e492a8077639.png">

**Comment by Albert-Gao** [comment]
## Everything below is ONLY for the web, the mobile modal pattern is solved at the OS layer

Hi, would love to help, but wonder what is the suggested solution, my quick idea is to solve this from the framework, which is, when you have a screen with option `{ presentation: "modal" }`, and you `link.push()` to this screen, 

- the `expo-router` would render this screen with [portal](https://reactjs.org/docs/portals.html) from the root.
- the path should not update to the modal path which would re-render the whole page and thus breaking the web-pattern (display the current page underneath the grayed-out background), it should just attach a query string maybe. (or it can?)

Then you can have a proper web-like modal for free and integrates with the `expo-router` default API.

The tricky part might be the grayed-out background, do we need to have a way to let the user reuse it, or let the user solve it at the user-land since with the above pattern, it is just a matter of implementation.

**Comment by EvanBacon** [comment]
Closing in favor of an internal linear ticket for our docs team. This should be pretty easy to do with Expo Router v3.

**Comment by yepes** [comment]
Any example of this use case?

**Comment by gstcarv** [comment]
Is it available on Expo Router V3?

**Comment by CodySwannGT** [comment]
Stumbled upon this. It appears that `presentation: modal` doesn't work on web, but can't find anything definitive in the docs

**Comment by yepes** [comment]
@EvanBacon what's the internal ticket? I'm playing with latest expo router and can't find a simple way to implement this

**Comment by betomoedano** [comment]
Hey, here's the doc describing this behavior: 
https://docs.expo.dev/router/advanced/modals/#web-modals-implementation
