### ISSUE TITLE
feat: pre-render static pages

### ISSUE THREAD

**Issue by EvanBacon** [expo/router#85]
Expo CLI should support rendering multiple HTML files, not just index.html. Running `npx expo export` for web should crawl the `app` directory, and statically render each file into a unique html file that will be output in the `dist` directory.

## Motivation

- Better web SEO for some pages. This is useful for improving [iOS spotlight search results](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/WebContent.html#//apple_ref/doc/uid/TP40016308-CH8-SW1).
- Slightly closer to removing the need to redirect all requests to the root `index.html`. To completely remove this we will need support for dynamic routes, which is out of scope for this feature.

## Requirements

- ~~This feature will require at least introducing [`externals`](https://webpack.js.org/configuration/externals/) support to Metro. This will enable us to render a bundle with Metro while keeping `react` intact (required for hooks).~~
- ~~Expo CLI implementing the Expo Router manifest spec and pre-rendering with Metro.~~
- ~~Probably more is needed, but this is where the feature is currently blocked.~~

**Comment by pronevich** [comment]
As Airbnb, Stripe use Metro to bundle web projects, is there something done in Metro to support common features(pre-rendering, splitting)  for web bundling?

**Comment by vemonet** [comment]
Anyone has an idea how to enable this basic feature? Otherwise the claim that expo-router can be used for the web is not right, and should be rectified in the doc

Static web pages are the heart and blood of the web! It is weird that after so many years, and so many different implementations of routers for React, this really basic and simple feature has not been supported yet (apart when using nextjs)

The documentation for metro is not really detailed: https://facebook.github.io/metro/ and seems mostly focused on android/ios and running servers, but not much about actually bundling an app that can have multiple entrypoints (apparently they don't have the concept that a web app can be accessed through multiple entrypoints), a quick search for keywords like "web" or "static" does not give anything interesting

Currently an easy fix would be to just run a simple post building step to duplicate the `dist/index.html` for every page found in the `app` folder

Here is a snippet to do it for all files and folders in the `app` folder (you will need to make changes to support nested folders), run it with `node` after generating the `dist/` folder:

```js
const appFolder = './app/';
const fs = require('fs');

const genRoutes = fs.readdirSync(appFolder)
  .map(file => file.split('.')[0].toLowerCase())
  .filter(file => file !== 'index');

genRoutes.forEach(route => {
  fs.copyFile('dist/index.html', `dist/${route}.html`, (err) => {
    if (err) throw err;
    console.log(`Generated static file for route ${route}`);
  });
})
```

Anyone got a better solution? Or is the `expo-router` team planning to implement support for the web in the future?

**Comment by EvanBacon** [comment]
@vemonet the feature is already on main in Expo CLI. If you want to see faster progress, feel free to contribute.

**Comment by EvanBacon** [comment]
Static generation is coming in v2 https://twitter.com/baconbrix/status/1656634369899888645?s=46&t=4GpE_iEDNlOGqhX9K_d56A

Here’s an example of how it performs: https://expo-twitter.netlify.app/

**Comment by EvanBacon** [comment]
Landed in SDK 49 alpha and the `expo-router@next` version: https://expo.github.io/router/docs/lab/static-rendering
