### ISSUE TITLE
Expo router  <SplashScreen />

### ISSUE THREAD

**Issue by fristyr** [expo/router#88]
Hi!

I want to ask if it is a known issue or not.
I still see a white screen after the Splash screen, for a second before I can see my app mounted.
This is my file system routes 
![photo_5935864053018770326_y](https://user-images.githubusercontent.com/33237937/196042311-c56acf58-87ca-4b25-aca1-1557d9e8aeeb.jpg)

And here is my **(root).tsx** file

```javascript
import React from 'react';
import {Layout, SplashScreen} from 'expo-router';
import {NativeBaseProvider} from 'native-base';
import {useLanguageService} from 'src/hooks';
import useCachedResources from 'src/hooks/useCachedResources';
import {useStore} from 'src/store';
import {custom_theme} from 'src/theme/custom-theme';
import Animated, {SlideInLeft} from 'react-native-reanimated';

export default function Root() {
  //Hooks
  const isLoadingComplete = useCachedResources();
  const {changeLanguage} = useLanguageService();
  //Store selectors
  const stored_lang = useStore.useLang();
  const hasHydrated = useStore.useHasHydrated();
  const isSignedIn = useStore.useIsSignedIn();

  React.useLayoutEffect(() => {
    if (hasHydrated) changeLanguage(stored_lang);
  }, [hasHydrated]);

  return (
    <React.Fragment>
      {/* When all loading is setup, unmount the splash screen component. */}
      {!isLoadingComplete && !hasHydrated && <SplashScreen />}
      
      {isLoadingComplete && hasHydrated && (
        <Animated.View entering={SlideInLeft} style={{flex:1}} >
          <NativeBaseProvider theme={custom_theme}>
            <Layout>
              <Layout.Screen
                name="(user)"
                redirect={!isSignedIn}
                options={{
                  headerShown: false,
                }}
              />
              <Layout.Screen
                name="(auth)"
                redirect={isSignedIn}
                options={{
                  headerShown: false,
                }}
              />

              <Layout.Children />
            </Layout>
          </NativeBaseProvider>
        </Animated.View>
      )}
    </React.Fragment>
  );
}

```

And my **useCachedResources** hook

```javascript
import {FontAwesome} from '@expo/vector-icons';
import * as Font from 'expo-font';
import {useEffect, useState} from 'react';

export default function useCachedResources() {
  const [isLoadingComplete, setLoadingComplete] = useState(false);

  // Load any resources or data that we need prior to rendering the app
  const loadResourcesAndDataAsync = async () => {
    try {
      // Load fonts
      await Font.loadAsync({
        ...FontAwesome.font,
        'space-mono': require('../assets/fonts/SpaceMono-Regular.ttf'),
        'Ubuntu-Bold': require('../assets/fonts/ubuntu-fonts/Ubuntu-Bold.ttf'),
        'Ubuntu-BoldItalic': require('../assets/fonts/ubuntu-fonts/Ubuntu-BoldItalic.ttf'),
        'Ubuntu-Italic': require('../assets/fonts/ubuntu-fonts/Ubuntu-Italic.ttf'),
        'Ubuntu-Light': require('../assets/fonts/ubuntu-fonts/Ubuntu-Light.ttf'),
        'Ubuntu-LightItalic': require('../assets/fonts/ubuntu-fonts/Ubuntu-LightItalic.ttf'),
        'Ubuntu-Medium': require('../assets/fonts/ubuntu-fonts/Ubuntu-Medium.ttf'),
        'Ubuntu-MediumItalic': require('../assets/fonts/ubuntu-fonts/Ubuntu-MediumItalic.ttf'),
        'Ubuntu-Regular': require('../assets/fonts/ubuntu-fonts/Ubuntu-Regular.ttf'),
      });
    } catch (e) {
      // We might want to provide this error information to an error-reporting service
      console.warn(e);
    } finally {
      setLoadingComplete(true);
    }
  };
  useEffect(() => {
    loadResourcesAndDataAsync();
  }, []);

  return isLoadingComplete;
}
```

And you can see the actual app in this video

https://user-images.githubusercontent.com/33237937/196042637-df1e1f00-3051-49b0-9d40-b20580720281.mp4

I am not 100% sure if this is an **expo-router** issue, sorry in advance

**Comment by EvanBacon** [comment]
Thanks for the detailed issue!

Splash Screen orchestration will unmount the native splash screen as soon as the app is capable of rendering content. This means the app is never shown in a state where you as the developer cannot render anything for some amount of time. In this video, it appears Splash Screen orchestration is working as expected. The issue is that your UI has a white background and the darker UI is animating after the splash has been revealed.

You can do either of these two things:

- Add a background color with React Native: `<React.Fragment>` -> `<View style={{ backgroundColor }}>` this will show while the other UI slides in.
- Change the native window background color in the [`app.json`](https://docs.expo.dev/versions/v46.0.0/config/app/#backgroundcolor) or using `expo-system-ui`.

**Comment by kylegwalsh** [comment]
@EvanBacon I just encountered this in my own app as well. I managed to resolve it, but ran into a few issues that I thought I'd mention here to help anyone else who encounters it.

> Add a background color with React Native: <React.Fragment> -> <View style={{ backgroundColor }}> this will show while the other UI slides in.

When I attempted this, I still had a white screen flash in before my root layout was rendered.

> Change the native window background color in the app.json or using expo-system-ui.

When I attempted this, it seemed to work perfectly (no flashing white screen). However, I noticed that when I was transitioning screens or triggering my keyboard avoiding view, I would see the bright Splash screen color render for a split second (which makes sense because it's the background color of the app at that point).

My final solution was to set the background color to match the Splash color in the `app.json` and then manually override the color back to white during my initialization with `SystemUI.setBackgroundColorAsync('white');`

Are there any plans to add back in the `expo-splash-screen` functionality to give people finer control over the SplashScreen hiding / showing logic?
